name: 'Terraform Cache'
description: 'Cache Terraform providers to improve workflow execution time.'

runs:
  using: 'composite'
  steps:
    - run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache
      shell: bash
    - uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
           ${{ runner.os }}-terraform-

branding:
  icon: 'archive'
  color: 'purple'
